### ISSUE TITLE
dashing package is missing dependencies

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2-gbp/ros1_bridge-release#5]
Follow-up of https://github.com/ros2-gbp/ros1_bridge-release/issues/4

The package in the testing repository (0.7.2-2) provide only a subset of message mappings compared to the crystal version and seems to be missing dependencies:

Message mapping:
Dashing:
```
$ ros2 run ros1_bridge dynamic_bridge --print-pairs | wc -l
71
```

Crystal:
```
$ ros2 run ros1_bridge dynamic_bridge --print-pairs | wc -l
164
```

It also doesnt export the ROS2 message packages as dependencies causing downstream packages to fail to build, e.g. http://build.ros2.org/job/Dbin_uB64__rosbag2_bag_v2_plugins__ubuntu_bionic_amd64__binary/1/console

```
$ apt-cache depends ros-dashing-ros1-bridge | grep dashing
ros-dashing-ros1-bridge
  Depends: ros-dashing-builtin-interfaces
  Depends: ros-dashing-rclcpp
  Depends: ros-dashing-rcutils
  Depends: ros-dashing-std-msgs
  Depends: ros-dashing-ros-workspace
```

Potential fix:
patch the package.xml in this repo to list ROS 2 message package dependencies, similar to the patches used in previous distributions https://github.com/ros2-gbp/ros1_bridge-release/tree/master/debian

**Comment by nuclearsandwich** [comment]
32029ccb2586fc930da197dc79f7885a60ea2d15 adds the interface packages in and https://github.com/ros/rosdistro/pull/21472 includes them in the release.

**Comment by mikaelarguedas** [comment]
Thanks @nuclearsandwich for the quick follow-up.

Unfortunately it appears that the new version (0.7.2-3) still has this issue:

```
$ apt-cache depends ros-dashing-ros1-bridge | grep dashing
ros-dashing-ros1-bridge
  Depends: ros-dashing-builtin-interfaces
  Depends: ros-dashing-rclcpp
  Depends: ros-dashing-rcutils
  Depends: ros-dashing-std-msgs
  Depends: ros-dashing-ros-workspace
```

Control file from the `debian/ros-dashing-ros1-bridge_0.7.2-3_bionic` tag:
https://github.com/ros2-gbp/ros1_bridge-release/blob/15d5aac98c1db15e4428e8bdd4a95d2056dcc6e0/debian/control#L11

---

@Karsten1987 FYI

**Comment by nuclearsandwich** [comment]
@mikaelarguedas yeah I noticed it as well. I haven't looked into it just yet. I'm unavailable today but will be looking into it tomorrow morning.

**Comment by nuclearsandwich** [comment]
It occurred to me this morning that I probably need to patch the release package.xml rather than the debian branch one. I'll give that a try and verify it before opening the PR.

**Comment by nuclearsandwich** [comment]
https://github.com/ros2-gbp/ros1_bridge-release/commit/d07b97bdb042ebab7dd0e97f83c5783d28d5b49b applies the commit to the release/dashing/ros1_bridge branch rather than the debian branch so it's actually used when resolving rosdeps. You can see the updated control file in https://github.com/ros2-gbp/ros1_bridge-release/blob/debian/ros-dashing-ros1-bridge_0.7.2-4_bionic/debian/control#L5

This has been released with https://github.com/ros/rosdistro/pull/21495

**Comment by mikaelarguedas** [comment]
Awesome! :tada:
